services:
  node:
    build:
      context: .
      target: development
    tty: true
    volumes:
      - .:/usr/src/app
    ports:
      - 3124:3124
    depends_on:
      - mysql
      - redis
  mysql:
    image: mysql:8.4
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: MY_DATABASE
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    volumes:
        # Where data is stored
      - mysql_storage:/var/lib/mysql
        # Reads database structure
      - ./config/mysql/:/docker-entrypoint-initdb.d/
    ports:
      - 3306:3306

  redis:
    image: redis:7.4.2
    restart: always
    volumes:
        - redis_storage:/data
    ports:
        - 6379:6379

volumes:
  mysql_storage:
  redis_storage:
