CREATE DATABASE IF NOT EXISTS LEARNING_MANAGEMENT_SYSTEM;

# Switch database
USE LEARNING_MANAGEMENT_SYSTEM;

# Create USERS table
CREATE TABLE IF NOT EXISTS USERS (
  id VARCHAR(255) NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  PRIMARY KEY (id)
);

# Create trigger for USERS table
CREATE TRIGGER ID_AS_UUID_USER BEFORE
INSERT
  ON USERS FOR EACH ROW
SET
  NEW.id = UUID();

# TABLE_EXAMPLE
#CREATE TABLE IF NOT EXISTS MY_TABLE (
#  id VARCHAR(255) NOT NULL,
#  userId VARCHAR(255) NOT NULL,
#  PRIMARY KEY (id),
#  UNIQUE (title, userId),
#  FOREIGN KEY (userId) REFERENCES USERS(id)
#);

